# grafana is disabled by default, but can be enabled by setting the following values.
# or proxy to an existing grafana: https://docs.kubecost.com/install-and-configure/advanced-configuration/custom-grafana
global:
  grafana:
    enabled: false
    proxy: false
# grafana:
#   image:
#     repository: YOUR_REGISTRY/grafana
#   sidecar:
#     image:
#       repository: YOUR_REGISTRY/k8s-sidecar

kubecostFrontend:
  image: registry1.dso.mil/ironbank/kubecost/frontend

kubecostModel:
  image: registry1.dso.mil/ironbank/kubecost/cost-model

forecasting:
  fullImageName: registry1.dso.mil/ironbank/kubecost/kubecost-modeling:v0.1.17

networkCosts:
  image:
    repository: registry1.dso.mil/ironbank/kubecost/kubecost-network-costs
    tag: v0.17.6

clusterController:
  image:
    # Kubecost cluster controller is not in Iron Bank
    repository: ""

prometheus:
  server:
    image:
      repository: registry1.dso.mil/ironbank/opensource/prometheus/prometheus

  configmapReload:
    prometheus:
      image:
        repository: registry1.dso.mil/ironbank/opensource/jimmidyson/configmap-reload

reporting:
  productAnalytics: false

