{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
spec:
  gateways:
  {{- range .Values.istio.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
    - {{ .Values.istio.host }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Release.Name }}-cost-analyzer
        port:
          number: 9090
{{- end }}
